1. We created the asyncWrapper function in order to create a placeholder for our try catch blocks which would be invoked on all of our controller methods 


2. const getTask = asyncWrapper(async (req, res, next) => {
  const { id: taskID } = req.params;
  const task = await Task.findOne({ _id: taskID });
  if (!task) {
            return next(createCustomError(`No task with id: ${taskID}`, 404)) 
  }
  res.status(200).json({ task });
});